# ==============================================================================
#                Default training configuration / hyper-parameters
# ==============================================================================


# ==============================================================================
#                        Optimizer & LR-scheduler configs
# ==============================================================================
# Max learning-rate. The starting LR given to the `Adam` optimizer. Defaults to 0.5.
max_lr: 0.5

# Min learning-rate to decay until. When this LR is reached, training will
# be stopped by our `EarlyStopHandler`.
# The `min_lr` param used by the `ReduceLROnPlateau` scheduler. Defaults to 1e-4.
min_lr: 1.0e-4

# Factor by which the learning rate will be reduced.
# The `factor` param used by the `ReduceLROnPlateau` scheduler. Defaults to 0.2.
reduce_lr_factor: 0.2

# Number of epochs with no improvement after which learning rate will be reduced.
# The `patience` param used by the `ReduceLROnPlateau` scheduler. Defaults to 3.
reduce_lr_patience: 3

# Threshold for measuring the new optimum, to only focus on significant changes.
# The `threshold` param used by the `ReduceLROnPlateau` scheduler. Defaults to 1e-2.
reduce_lr_threshold: 1.0e-2


# ==============================================================================
#                                  Misc. configs
# ==============================================================================
# Whether to disable the adversarial check. Defaults to False.
disable_adv_check: False

# Perform adversarial check every `num_epoch_adv_check` epochs. Only has an effect when
# `disable_adv_check=False`. Defaults to 10.
num_epoch_adv_check: 10

# Whether to disable tqdm's progress bar during training. Defaults to False.
disable_progress_bar: False
